name: build

on: [push]

jobs:
  coding-standards:
    name: Coding Standards Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress
      - name: Run ecs check
        run: vendor/bin/ecs check
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress
      - name: Install PHPUnit
        run: vendor/bin/simple-phpunit install
      - name: Run PHPStan analyse
        run: vendor/bin/phpstan analyse
      - name: Run Psalm analyse
        run: vendor/bin/psalm
  test:
    name: Tests (${{ matrix.entry }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        entry:
          - 8.1
          - 8.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.entry }}
          coverage: none
      - name: Initialize tests
        run: make initialize
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress
      - name: Run tests
        run: |
          vendor/bin/simple-phpunit install
          vendor/bin/simple-phpunit
  coverage:
    name: Tests Coverage
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: pcov
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress
      - name: PHPUnit run with coverage
        run: |
          vendor/bin/simple-phpunit install
          vendor/bin/simple-phpunit --testsuite=Unit --coverage-clover=clover.xml
      - name: Upload coverage report
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: clover.xml
