name: build

on: [push]

jobs:
  ecs:
    name: Easy Coding Standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ecs-${{ github.sha }}
          restore-keys: ecs-
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Easy Coding Standard run
        run: vendor/bin/ecs check
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: phpstan-${{ github.sha }}
          restore-keys: phpstan-
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Install PHPUnit
        run: vendor/bin/simple-phpunit install
      - name: PHPStan run
        run: vendor/bin/phpstan analyse
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.1', '8.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - name: Initialize tests
        run: make initialize
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php-versions }}-phpunit-${{ github.sha }}
          restore-keys: ${{ matrix.php-versions }}-phpunit-
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Run tests
        run: |
          vendor/bin/simple-phpunit install
          vendor/bin/simple-phpunit
  coverage:
    name: Tests coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: pcov
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: cov-${{ github.sha }}
          restore-keys: cov-
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: PHPUnit run with coverage
        run: |
          vendor/bin/simple-phpunit install
          vendor/bin/simple-phpunit --testsuite=Unit --coverage-clover=clover.xml
      - name: Upload coverage report
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: clover.xml
