name: build

on: [push]

jobs:
  coding-standards:
    name: Coding Standards Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress
      - name: Run ecs check
        run: vendor/bin/ecs check
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress
      - name: Install PHPUnit
        run: vendor/bin/simple-phpunit install
      - name: Run PHPStan analyse
        run: vendor/bin/phpstan analyse
  test:
    name: Tests (${{ matrix.entry.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        entry:
          - { php: 8.1, allowed-failure: false }
          - { php: 8.2, allowed-failure: true }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.entry.php }}
          coverage: none
      - name: Initialize tests
        run: make initialize
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress
      - name: Run tests
        run: |
          vendor/bin/simple-phpunit install
          vendor/bin/simple-phpunit
        continue-on-error: ${{ matrix.entry.allowed-failure }}
  coverage:
    name: Tests coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: pcov
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress
      - name: PHPUnit run with coverage
        run: |
          vendor/bin/simple-phpunit install
          vendor/bin/simple-phpunit --testsuite=Unit --coverage-clover=clover.xml
      - name: Upload coverage report
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: clover.xml
