name: CI

on: [push]

jobs:
  ecs:
    name: ECS
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress
      - name: Run ecs check
        run: vendor/bin/ecs check
  rector:
    name: Rector
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress
      - name: Run ecs check
        run: vendor/bin/rector process --dry-run
  phpstan:
    name: PHPStan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress
      - name: Run analyse
        run: vendor/bin/phpstan analyse --memory-limit 2G
  psalm:
    name: Psalm
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress
      - name: Run analyse
        run: vendor/bin/psalm
  tests:
    name: Tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        dependencies:
          - highest
          - locked
        operating-system:
          - ubuntu-latest
        php-version:
          - 8.2
          - 8.3
          - 8.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - name: Initialize tests
        run: make initialize
      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --no-ansi --no-interaction --no-progress
      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite Unit
      - name: Run integration tests
        run: vendor/bin/phpunit --testsuite Integration
  coverage:
    name: Tests Coverage
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: pcov
      - name: Initialize tests
        run: make initialize
      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress
      - name: PHPUnit run with coverage
        run: vendor/bin/phpunit --coverage-clover=clover.xml
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: clover.xml
          verbose: true
