name: CI

on: [push]

jobs:
  ecs:
    name: Easy Coding Standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ecs-${{ github.sha }}
          restore-keys: ecs-
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Easy Coding Standard run
        run: vendor/bin/ecs check
