name: CI

on: [push]

jobs:
  ecs:
    name: Easy Coding Standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ecs-${{ github.sha }}
          restore-keys: ecs-
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Easy Coding Standard run
        run: vendor/bin/ecs check
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: phpstan-${{ github.sha }}
          restore-keys: phpstan-
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Install PHPUnit
        run: vendor/bin/simple-phpunit install
      - name: PHPStan run
        run: vendor/bin/phpstan analyse
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialize tests
        run: make initialize
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: phpunit-${{ github.sha }}
          restore-keys: phpunit-
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Run tests
        run: |
          vendor/bin/simple-phpunit install
          vendor/bin/simple-phpunit
